{% set provider = "Triton" %}
{% set goname = "github.com/terraform-providers/terraform-provider-"+provider.lower() %}
{% set version = "0.5.1" %}

{% set name = goname.split('/')[-1] %}

{% set x4_plugin = name + '_v' + version + "_x4" %}

{% set sha256 = "bb4237794a5ca52fbf8968cdcac36f7b1976d1c7f5665f4e99ef5cbb1ccb03a2" %}
{% set sha256_win64 = "7095121a1f1341e8f0e04cbecc3c2f279a585f94ee9dffcfbe12b79b2c710846" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://{{ goname }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 1002
  script:
    - go build -v -o {{ target_gobin }}{{ x4_plugin }}{{ target_goexe }}

requirements:
  build:
    - {{ compiler('go') }} 1.13
  run:
    - terraform 0.12

test:
  commands:
    # Create a sample init.tf loading the provider
    - echo 'provider "{{ provider|lower }}" { version="{{ version }}" }' > init.tf  # [unix]
    - echo provider "{{ provider|lower }}" { version="{{ version }}" } > init.tf    # [win]

    # Initialize
    - terraform init

    # Tests that init was successful
    - test -f .terraform/plugins/{{ target_goos }}_{{ target_goarch }}/lock.json              # [unix]
    - if not exist .terraformplugins{{ target_goos }}_{{ target_goarch }}lock.json exit 1  # [win]

    # Test that the provider was not downloaded
    - test ! -f .terraform/plugins/{{ target_goos }}_{{ target_goarch }}/{{ x4_plugin }}{{ target_goexe }}        # [unix]
    - if exist .terraformplugins{{ target_goos }}_{{ target_goarch }}{{ x4_plugin }}{{ target_goexe }} exit 1  # [win]

about:
  home: https://www.terraform.io
  license: MPL-2.0
  summary: The Terraform {{ provider }} provider
  doc_url: https://www.terraform.io/docs/providers/{{ provider|lower }}/index.html
  dev_url: https://github.com/terraform-providers/{{ name }}

extra:
  recipe-maintainers:
    - conda-forge/terraform
