appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: lwoALxKzQ0xhWlGmbxhVeS5ysCmZTFe9QazNx9khsA+aLoJWwjSky20rIqUE8NV045HJgcIWux6LXqLV31rNqeRtIptSzkgz3FrNPI4b1u4nDQXwWbJbvi3Gg55WqM47JuRUz080sYsdq9o0boyKw3k2y+71d1K0E8y7SDXo00MIdhqrHYmMSDXtewLfB3YK4XfdyKUS2O9vJoojedTCEZPhCX3BuXcy/fjE1nYoqZI0I/ci44ZxM4o/EwcOdID2C0UxJiDackpaHRFoLbzD86IpCE6SQR9kM79/Aik7SjkUZgggy9j3DtYojeXe8vgGBVdH8+W3OyMlxATm7J1tqcIlOXklnHmpn6KewAb85oxA2WHj/hAfhT59LG+Y7plyg+c9dkywkYLdmNmKV0/3PtsN+wi8yI/E0zPNYUstV+/hE0BkQqCHlUr3putXGeZYTzBugH0ojJl0qhs8p44AvHhlMJhva/1x+1h27w7qMTT3x0dp2f6kizqCru2h7IZjhiEDY0Al9SG/NWCmtp1/ro5M/DylaLebOqSYcKRvys3hUHR6VbNkxbkB9nZ0gJEChkkpy/EygCXciqQvpsJ3al4v0rLDggFF45ZNCmnC9/9VHKrPrGFPkow8MG1B7N+XImGjIO1EwBjTOCrl/OQLiXHkJf9NDB0r0K46KA1NRno=}
provider:
  win: azure
